# Generated by Django 3.0.4 on 2020-03-20 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webroot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exp',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
