# Generated by Django 3.0.4 on 2020-03-23 21:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webroot', '0003_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.BigIntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
